In [63]:
# 1. Importing Libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.set_option('display.max_colwidth', None)

import plotly.graph_objects as go
from plotly.offline import iplot
import plotly.express as px
from plotly.offline import init_notebook_mode
init_notebook_mode(connected = True)

import math
from collections import Counter
import scipy.stats as ss
from scipy.stats import pearsonr

In [3]:
import category_encoders as ce
from sklearn import preprocessing

from sklearn.model_selection import train_test_split, RepeatedKFold, RepeatedStratifiedKFold, cross_validate, cross_val_predict

from sklearn.preprocessing import StandardScaler, Normalizer, OneHotEncoder

from sklearn.feature_selection import SelectKBest, chi2, mutual_info_classif


from sklearn import metrics
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score, roc_auc_score
from sklearn.metrics import  plot_precision_recall_curve, plot_roc_curve, plot_confusion_matrix
    
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier 

from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

import warnings
warnings.filterwarnings('ignore')

In [82]:
df_test_actual = pd.read_csv('Test Dataset.csv')

In [47]:
def inc_occ(occupation, gender):
    if occupation =='Armed-Forces':
        if gender == 'Male':
            return 51844
        else:
            return 41903
    elif occupation =='Protective-serv':
        if gender == 'Male':
            return 55317
        else:
            return 34206
    elif occupation =='Priv-house-serv': 
        if gender == 'Male':
            return 26822
        else:
            return 16811
    elif occupation =='Other-service':
        if gender == 'Male':
            return 22219
        else:
            return 20788
    elif occupation =='Farming-fishing':
        if gender == 'Male':
            return 26822
        else:
            return 16811
    elif occupation =='Prof-specialty':
        if gender == 'Male':
            return 72039
        else:
            return 50711
    elif occupation =='Machine-op-inspct':
        if gender == 'Male':
            return 39372
        else:
            return 34335
    elif occupation =='Sales':
        if gender == 'Male':
            return 48908
        else:
            return 24920
    elif occupation =='Transport-moving':
        if gender == 'Male':
            return 33292
        else:
            return 23157
    elif occupation =='Exec-managerial':
        if gender == 'Male':
            return 80366
        else:
            return 60576
    elif occupation =='Handlers-cleaners':
        if gender == 'Male':
            return 28163
        else:
            return 18701
    elif occupation =='Craft-repair':
        if gender == 'Male':
            return 42807
        else:
            return 27609
    elif occupation =='Adm-clerical':
        if gender == 'Male':
            return 39372
        else:
            return 34335
    elif occupation =='Tech-support':
        if gender == 'Male':
            return 48908
        else:
            return 24920

In [48]:
def inc_age(agrp,gender):
    if agrp == '0-25':
        if gender == 'Male':
            return 20757
        else:
            return 18964
    elif agrp == '25-35':
        if gender == 'Male':
            return 54139
        else:
            return 42510

    elif agrp == '35-45':
        if gender == 'Male':
            return 79132
        else:
            return 53500
    elif agrp == '45-55':
        if gender == 'Male':
            return 86724
        else:
            return 57151
    elif agrp == '55-65':
        if gender == 'Male':
            return 81676
        else:
            return 49168
    else:
        if gender == 'Male':
            return 58576
        else:
            return 35316

In [49]:
def inc_rel(relation, gender):
    if relation =='Husband' or relation =='Wife' :
        if gender == ' Male':
            return 55727
        else:
            return 33198
    if relation =='Other-relative':
        if gender == 'Male':
            return 25416
        else:
            return 20601
    if relation =='Own-child':
        if gender == 'Male':
            return 16471
        else:
            return 14152
    if relation =='Unmarried'or relation == 'Not-in-family':
        if gender == 'Male':
            return 52271
        else:
            return 31968

In [50]:
def inc_ms(status, gender):
    

    if status =='Married-civ-spouse' or status =='Married-AF-spouse' :
        if gender == 'Male':
            return 57404
        else:
            return 32743
    if status =='Widowed' or status == 'Separated':
        if gender == 'Male':
            return 42286
        else:
            return 34502
    if status =='Married-spouse-absent':
        if gender == 'Male':
            return 37764
        else:
            return 26408
    if status =='Divorced':
        if gender == 'Male':
            return 42286
        else:
            return 34502
    if status =='Never-married':
        if gender == 'Male':
            return 28581
        else:
            return 26420

In [51]:
def inc_ed(education, gender):
    
        
    if education =='Doctorate' :
        if gender == 'Male':
            return 106472
        else:
            return 86047
    elif education =='Prof-school' :
        if gender == 'Male':
            return 127625
        else:
            return 82093
    elif education =='Masters' :
        if gender == 'Male':
            return 88280
        else:
            return 66601
    elif education =='Bachelors' :
        if gender == 'Male':
            return 69505
        else:
            return 45942
    
    elif education =='Assoc-voc' or education == 'Assoc-acdm':
        if gender == 'Male':
            return 51250
        else:
            return 31652
    elif education =='Some-college' :
        if gender == 'Male':
            return 45639
        else:
            return 28653
    elif education =='HS-grad' :
        if gender == 'Male':
            return 37144
        else:
            return 22052
    else :
        if gender == 'Male':
            return 24420
        else:
            return 13129

In [52]:
def inc_work(workclass, occupation, gender):

        
    if workclass =='Private' :
        if gender == 'Male':
            if occupation == 'Farming-fishing':
                return 30231
            else:
                return 46956
        else:
            if occupation == 'Farming-fishing':
                return 21440
            else:
                return 34321
    if workclass =='Self-emp-inc' or workclass =='Self-emp-not-inc' :
        if gender == 'Male':
            if occupation == 'Farming-fishing':
                return 36081
            else:
                return 50380
        else:
            if occupation == 'Farming-fishing':
                return 25083
            else:
                return 30393
    if workclass =='Local-gov' or workclass == 'State-gov' :
        if gender == 'Male':
            return 55030
        else:
            return 42460
    if workclass =='Federal-gov' :
        if gender == 'Male':
            return 66964
        else:
            return 60727
    else:
        return 0

In [83]:

# EXTRACTING AGE FEATURE
df_test_actual['age']=2021-pd.to_datetime(df_test_actual['date_of_birth']).dt.year
df_test_actual=df_test_actual.drop('date_of_birth',axis=1)

def modify_age(t):
    if t<0:
        return t+100
    else:
        return t
    
df_test_actual['Age']=df_test_actual.age.apply(modify_age)
df_test_actual['age_group'] = pd.cut(df_test_actual.Age, bins=[0,25,35,45,55,65,75,99], labels =['0-25','25-35','35-45','45-55','55-65','65-75','75-99'])

# EXTRACTIUNG EDUCATION GROUP
df_test_actual['edu_group'] = pd.cut(df_test_actual.education_num, bins=[0,2,6,8,10,12,13,14,17], labels =['pre','matri','hs','diplo','asso','grad','pg','phd'])

# EXTRACTING NET CAPITAL GAIN
df_test_actual['net_cap_gain'] = df_test_actual['capital_gain']-df_test_actual['capital_loss']

# EXTRACTING INCOME FEATURE
df_test_actual['income_ed'] = df_test_actual.apply(lambda x: inc_ed(x.education_level, x.gender), axis=1)     
df_test_actual['income_occ'] = df_test_actual.apply(lambda x: inc_occ(x.occupation, x.gender), axis=1)
df_test_actual['income_age'] = df_test_actual.apply(lambda x: inc_age(x.age_group, x.gender), axis=1)
df_test_actual['income_rel'] = df_test_actual.apply(lambda x: inc_rel(x.relationship, x.gender), axis=1)    
df_test_actual['income_workclass'] = df_test_actual.apply(lambda x: inc_work(x.workclass, x.occupation, x.gender), axis=1)    
df_test_actual['income_mar_st'] = df_test_actual.apply(lambda x: inc_ms(x.marital_status, x.gender), axis=1)

df_test_actual['income_occ_age'] = (df_test_actual['income_occ']+df_test_actual['income_age'])/2
df_test_actual['net_income_occ_age_edu'] = (((df_test_actual['income_ed'] + df_test_actual['income_occ_age'])/2))


# MISSING VALUE IMPUTATION
df_test_actual['inquiry_purpose_code'] = df_test_actual['inquiry_purpose_code'].fillna(13.0)
df_test_actual['asset_code'] = df_test_actual['asset_code'].fillna(1)
df_test_actual['portfolio_type'] = df_test_actual['portfolio_type'].fillna('R')
df_test_actual['asset_class_cd'] = df_test_actual['asset_class_cd'].fillna(-1)

# CONVERTING TO CATEGORY
df_test_actual['inquiry_purpose_code'] = df_test_actual.inquiry_purpose_code.astype('category')
df_test_actual['institute_type'] = df_test_actual.institute_type.astype('category')
df_test_actual['account_type'] = df_test_actual.account_type.astype('category')
df_test_actual['asset_class_cd'] = df_test_actual.asset_class_cd.astype('object')
df_test_actual['asset_code'] = df_test_actual.asset_code.astype('object')
df_test_actual['portfolio_type']= df_test_actual.portfolio_type.astype('object')
df_test_actual['relationship']= df_test_actual.relationship.astype('object')
df_test_actual['marital_status']= df_test_actual.marital_status.astype('object')

In [84]:
df_test_actual['income_occ_age'] = (df_test_actual['income_occ']+df_test_actual['income_age'])/2
df_test_actual['net_income_occ_age_edu'] = (df_test_actual['income_occ_age']+ df_test_actual['income_ed'])/2
df_test_actual['income'] = np.log(df_test_actual['net_income_occ_age_edu'])

# Determining encoders

In [55]:
df = pd.read_csv('ABC_payments_bank_credcard_train.csv')

# 6. EDUCATINO GROUPS
df['edu_group'] = pd.cut(df.education_num, bins=[0,2,6,8,10,12,13,14,17], labels =['pre','matri','hs','diplo','asso','grad','pg','phd'])


df['gender'] = df['gender'].str.strip()
df['occupation'] = df['occupation'].str.strip()
df['relationship'] = df['relationship'].str.strip()
df['marital_status'] = df['marital_status'].str.strip()
df['education_level'] = df['education_level'].str.strip()
df['workclass'] = df['workclass'].str.strip()


df['asset_class_cd'] = df['asset_class_cd'].fillna(df['asset_class_cd'].mode()[0])

# 9. Imputing inquiry purpose code
df['inquiry_purpose_code'] = df['inquiry_purpose_code'].fillna(df['inquiry_purpose_code'].mode()[0])


#10. Imputing asset code
df['asset_code'] = df['asset_code'].fillna(df['asset_code'].mode()[0])


#11. Imputation portfolio type
df['portfolio_type'] = df['portfolio_type'].fillna(df['portfolio_type'].mode()[0])


df['inquiry_purpose_code'] = df.inquiry_purpose_code.astype('category')
df['institute_type'] = df.institute_type.astype('category')
df['account_type'] = df.account_type.astype('category')
df['asset_class_cd'] = df.asset_class_cd.astype('object')
df['asset_code'] = df.asset_code.astype('object')
df['portfolio_type']= df.portfolio_type.astype('object')

In [56]:

targ_col1 = ['account_type','edu_group','asset_code','inquiry_purpose_code','institute_type', 'occupation','relationship','marital_status','workclass']
label_col1 = ['gender']


encoder1 = ce.TargetEncoder(smoothing = 850) 
df[targ_col1] = encoder1.fit_transform(df[targ_col1], df['approved'])

encoder2 = ce.OrdinalEncoder(return_df=True)
df[label_col1] = encoder2.fit(df[label_col1])

# Prediction using LGBM model

In [34]:
import pickle
model_lgbm = pickle.load(open('tuned_lgbm_model.pkl', 'rb'))

In [85]:
df_test_actual[targ_col1] = encoder1.transform(df_test_actual[targ_col1])
df_test_actual[label_col1] = encoder2.transform(df_test_actual[label_col1])

In [86]:
model_col = targ_col1 + label_col1 + ['hours_per_week', 'income', 'net_cap_gain','Age']

y_pred_test = (model_lgbm.predict_proba(df_test_actual[model_col]))

dumm_df = pd.DataFrame(y_pred_test, columns = ['prob_0','prob'])
df_test_actual = pd.merge(df_test_actual, dumm_df['prob'], left_index=True, right_index=True)

In [87]:
df_test_actual['pred_app']=-1
for i in df_test_actual.index:
    if df_test_actual['prob'][i] > 0.42:
        df_test_actual['pred_app'][i] = 1
    else:
        df_test_actual['pred_app'][i] = 0

In [88]:
# Considering weighted average of squares
df_test_actual['net_income'] = (10*df_test_actual['income_age']+80*df_test_actual['net_cap_gain'] +200*df_test_actual['income_ed'] + 110*df_test_actual['income_mar_st'] + 50*df_test_actual['income_rel']+ 540*df_test_actual['income_occ'] +70*df_test_actual['income_workclass'] )

max_net_income = 89240260


a=0.35
df_test_actual['credit'] = (df_test_actual['net_income']*a/(max_net_income)+df_test_actual['prob']*(1-a))*8000
df_test_actual['credit'] = df_test_actual['credit'].apply(lambda x: 1000 if x < 3000 else 8000 if x>5800 else x)

In [89]:
# Converting credit to nearest 500
import math

df_test_actual['credit'] = df_test_actual['credit'].apply(lambda x: math.ceil(x / 500.0) * 500.0)

In [ ]:
df_test_actual['label'] = 1
for j in df_test_actual.index:
    if ((df_test_actual['pred_app'][j] == 0) & (df_test_actual['approved'][j] == 0)):
        df_test_actual['label'][j] = 'TN'

    elif  ((df_test_actual['pred_app'][j] == 1) & (df_test_actual['approved'][j] == 1)):
        df_test_actual['label'][j] = 'TP'

    elif  ((df_test_actual['pred_app'][j] == 1) & (df_test_actual['approved'][j] == 0)):
        df_test_actual['label'][j] = 'FP'

    elif  ((df_test_actual['pred_app'][j] == 0) & (df_test_actual['approved'][j] == 1)):
        df_test_actual['label'][j] = 'FN'

revenue = df_test_actual[df_test_actual['label']=='TP']['credit'].sum()
psuedo_loss = df_test_actual[df_test_actual['label']=='FN']['credit'].sum()
actual_loss = df_test_actual[df_test_actual['label']=='FP']['credit'].sum()
total_credit = df_test_actual['credit'].sum()


print('Revenue :',revenue, revenue/total_credit*100,'\nPsuedo loss:',psuedo_loss, psuedo_loss/total_credit*100,'\nActual loss:', actual_loss, actual_loss/total_credit*100 )
print('profit', revenue-psuedo_loss-actual_loss)

In [90]:
df_final = df_test_actual[['user_id', 'prob', 'pred_app', 'credit']]

In [91]:
df_final.to_csv('Final_user_credit.csv')